### ISSUE TITLE
VK api updates

### ISSUE THREAD

**Issue by lgg** [lgg/vk-to-telegram-bot#16]
* use https://vk.com/dev/wall.getById
* maybe use service token? (https://vk.com/dev/access_token) and (https://vk.com/dev/service_token)

**Comment by admdc2000** [comment]
Fail loading data from VK: -XXXXXXXXXX More info: {"error":{"error_code":8,"error_msg":"Invalid request: method is unavailable without access token","request_params":[{"key":"oauth","value":"1"},{"key":"method","value":"wall.get"},{"key":"v","value":"5.50"},{"key":"owner_id","value":"-XXXXXXXXXX"},{"key":"count","value":"5"}]}}

**Comment by lgg** [comment]
@admdc2000 i know about this issue. Will fix as soon as possible.

**Comment by lgg** [comment]
fixed with fc468ffe1db988b266cd2bd9b606a1a3af765b93 

more info will be soon

**Comment by lgg** [comment]
fixed in v1.0.0
