### ISSUE TITLE
Add to docs how to setup multisources-multidest config.

### ISSUE THREAD

**Issue by D4rk4** [lgg/vk-to-telegram-bot#32]

**Comment by lgg** [comment]
@D4rk4 you mean (few VK sources =>(to) few telegram sources) in one config section?

**Comment by D4rk4** [comment]
Yes, i think you must add some examples to documentation

**Comment by lgg** [comment]
This feature is not fully implemented yet. Watch #7 and #8 for updates

**Comment by Badiboy** [comment]
I simply add TWO config records first from group A to channel and second from groub B to channel and it works. I don't know if it's defined bahaviour or a lifehack... :)

>     private static $configs = [
>        [
>            //VK
>            "vk" => "-xxx1",
>            ....
>            "t_chat" => "BadiX",
>            ....
>        ],
>        [
>            //VK
>            "vk" => "-xxx2",
>            ....
>            "t_chat" => "BadiX",
>            ....
>            ],
>     ];

**Comment by lgg** [comment]
@Badiboy it's ok, it is how this script should work.

**Comment by lgg** [comment]
Will fix with 2.0, check #38
