### ISSUE TITLE
Не пересылаются прикрепленные изобрадения

### ISSUE THREAD

**Issue by andrychuyko** [lgg/vk-to-telegram-bot#42]
Вот конфиг

            "messageSend" => [
                "disable_web_page_preview" => true,
                "disable_notification" => false
            ],
            //Bot-manager settings
            //Bot-manager reposting params(modes)
            "extended" => [
                "active" => true,
                "needLink" => true,
                "resendAttachments" => true,
            ],
            "needPostPreview" => true,
            //Bot-manager internal functions params
            "language" => "ru",
            "textCutter" => [
                "aggressive" => false,
                "limit" => 3
            ],
            "vkLinks" => [
                "show" => false,
                "symbols" => [
                    "open" => "[",
                    "close" => "]"
                ]
            ]

Вот пост https://vk.com/russmoroz?w=wall438401560_34194
В телеграм пришел только текст

**Comment by lgg** [comment]
closed via #43
