### ISSUE TITLE
Помощь в документации (не запускается бот).

### ISSUE THREAD

**Issue by euppi98** [lgg/vk-to-telegram-bot#49]
В общем вроде бы сделал все условия. Но посты так в телеги и не появляются…
>  //VK
            "vk" => "-173697340",
            "vk_token" => "a1607949a1607949a13526fb9ba1068d75aa160a1607949fa875bdbafd25745c795****",
            //Telegram
            "t_key" => "719183816:AAE-vmYDZGNSJmRnycMCUchBq4MJQV6j0mc",
            "t_name" => "test_not_euppi98_1_bot",
            "t_chat" => "test_1_euppi98",

Хостинг использую mchost.ru
Сам домен - https://signal-exchange.mcdir.ru
Планировщик:
![screen shot 2018-11-10 at 22 16 31](https://user-images.githubusercontent.com/23306157/48305131-62009480-e536-11e8-84c2-823344ffdd4a.png)
От планировщика по почте получаю вот такой ответ:
`/bin/sh: /home/httpd/vhosts/signal-exchange.mcdir.ru/httpdocs/vk-to-telegram-bot: is a directory `

**Comment by euppi98** [comment]
Хостинг использую mchost.ru
Сам домен - https://signal-exchange.mcdir.ru/vk-to-telegram-bot/
Планировщик:
![screen shot 2018-11-10 at 22 16 31](https://user-images.githubusercontent.com/23306157/48305131-62009480-e536-11e8-84c2-823344ffdd4a.png)

**Comment by euppi98** [comment]
Выставил ехо
```
<?php
echo "1 \n";
require_once "vendor/autoload.php";

echo "2 \n";
//Create manager
$manager = new Manager();

echo "3 \n";
//Start manager
$manager->start();

echo "4 \n";
```
Проходит код лишь до 3 ехо.

**Comment by lgg** [comment]
@euppi98 в команде крона упущена `cd`
То есть должно быть так: `cd /home/httpd/vhosts/signal-exchange.mcdir.ru/httpdocs/vk-to-telegram-bot && php index.php`

По поводу того, что тормозит на 2 эхо - нужно логи смотреть. Логи apache/nginx.

ps
Советую вместо хостинга использовать VPS: vultr.com или digitalocean.com (на этом, если Вы студент можете получить 50$ на счёт, благодаря Github Education).

**Comment by lgg** [comment]
@euppi98 а стоп, в планировщике вон вверху написано, что для запуска php скриптов надо использовать `php-cli`
![image](https://user-images.githubusercontent.com/12018713/48317347-8a08fa00-e601-11e8-9322-8b7cafa4c78c.png)

**Comment by euppi98** [comment]
+ логи от Telegram Messenger
```
[Mon Nov 12 11:25:16 2018] [error] [client 149.154.167.161] File does not exist: /home/httpd/vhosts/signal-exchange.mcdir.ru/httpdocs/httpdocs
[Mon Nov 12 11:25:34 2018] [error] [client 149.154.167.163] File does not exist: /home/httpd/vhosts/signal-exchange.mcdir.ru/httpdocs/httpdocs
```

**Comment by euppi98** [comment]
...

**Comment by euppi98** [comment]
Так исправил крон, все теперь работает как надо... Спасибо за помощь.
